version: "3.8"

services:
  angular:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.angular
      args:
        - IMAGE_TAG=${ANGULAR_IMAGE_TAG}
    container_name: ${ANGULAR_CONTAINER_NAME}
    volumes:
      - ./front:/usr/src/app:rw

  nginx:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        - IMAGE_TAG=${NGINX_IMAGE_TAG}
    container_name: ${NGINX_CONTAINER_NAME}
    volumes:
      - ./front/helloWorld/dist:/var/www/html/app/:rw
      - ./api/helloWorld:/var/www/html/api/:rw
    ports:
      - ${NGINX_ANGULAR_EXTERNAL_PORT}:${NGINX_ANGULAR_INTERNAL_PORT}
      - ${NGINX_API_EXTERNAL_PORT}:${NGINX_API_INTERNAL_PORT}

  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - IMAGE_TAG=${NODE_API_IMAGE_TAG}
    container_name: ${NODE_API_CONTAINER_NAME}
    volumes:
      - ./api/helloWorld:/usr/src/api:rw
